### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by lyrixx** [vyuldashev/monolog-loki#1]
Yeah! This looks nice and very promising.

Does it work wells?

Do you plant to contribute it to monolog?

**Comment by vyuldashev** [comment]
@lyrixx Hello, I am still playing with Loki. I tested it in small project and it works.
Not sure about contributing it to monolog directly. Loki needs to become stable firstly I guess.

**Comment by lyrixx** [comment]
Thanks. I tried it too, and for now I keep using ES 
see https://github.com/Seldaek/monolog/pull/1334
